udalil Practice/ dobavil class
Erl0711/PracticeTask pull request #26
Opened 2024-03-01 05:15 UTC by Asan4304

2024-03-01 06:24 UTC, Erl0711 requested changes
Комент оставил

2024-03-01 06:24 UTC, Erl0711 commented on src/main/java/org/practice/tasks/AsanC/warmup1/MonkeyTrouble.java
> +        if(aSmile == true && bSmile == true || aSmile == false && bSmile == false){
aSmile == true некорректное написание, если ты хочешь проверить на true так как это boolean просто пиши aSmile это зхначит типа aSmile == true под капотом. Если false то !aSmile// Исправить!!!

2024-03-01 06:27 UTC, Asan4304 commented on src/main/java/org/practice/tasks/AsanC/warmup1/MonkeyTrouble.java
> +        if(aSmile == true && bSmile == true || aSmile == false && bSmile == false){
ок

2024-03-02 10:26 UTC, Erl0711 approved these changes

2024-03-04 16:31 UTC, merged